Score documents: Document selection and selection output
biolab/orange3-text pull request #710
Opened 2021-08-17 13:15 UTC by PrimozGodec

##### Issue

Score documents widget is missing selection

##### Description of changes
Implemented selection in the table view and the `Selected documents` output

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

2021-08-20 10:28 UTC, VesnaT reviewed
1. The selection use usually considered as a schema_only setting.
2. Have you considered adding a selection box. Something like:
![image](https://user-images.githubusercontent.com/11465003/130215573-f716b01e-cd57-455d-9458-4ec445290b18.png)

2021-08-20 10:28 UTC, VesnaT commented on orangecontrib/text/widgets/owscoredocuments.py
> +from Orange.widgets.utils.annotated_data import create_annotated_table
It would be nicer, if the imports were more structured.

2021-08-20 11:19 UTC, PrimozGodec commented
> The selection use usually considered as a schema_only setting.

Totally forgot that it would be nice if the selection is remembered. Will implement it

> Have you considered adding a selection box. Something like:

I do not like selection boxes too much, since users can easily do selection in the table itself, but if other widgets have them I can also implement it here. 

> It would be nicer, if the imports were more structured.

I forgot to run isort on this one. Will fix it.

2021-09-06 07:19 UTC, VesnaT requested changes

2021-09-06 07:19 UTC, VesnaT commented on orangecontrib/text/widgets/owscoredocuments.py
> +    ITEMS = "None", "All", "Manual", "Top words"
Considering the widget scores the documents, `Top words` should be renamed to `Top documents`.

2021-09-06 07:19 UTC, VesnaT commented on orangecontrib/text/widgets/owscoredocuments.py
> +        box = gui.vBox(self.controlArea, "Select Words")
`Select Words` -> `Select Documents` 
`self.controlArea` -> `self.buttonsArea`

2021-09-06 10:09 UTC, merged