Annotated Corpus Map: New widget
biolab/orange3-text pull request #818
Opened 2022-04-19 07:31 UTC by VesnaT

##### Issue

Implements #799

##### Description of changes

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

2022-04-22 13:51 UTC, ajdapretnar commented
I propose to have a shorter name for the widget. Perhaps "Corpus Annotator"? Or "Document Annotation"? "Semantic Annotation"? @BlazZupan?

2022-04-25 14:14 UTC, ajdapretnar commented
It would be great if the widget included a legend showing which color pertains to which cluster.

2022-05-04 11:50 UTC, PrimozGodec commented
/rebase

2022-05-04 11:52 UTC, PrimozGodec requested changes

2022-05-04 11:52 UTC, PrimozGodec commented on orangecontrib/text/widgets/owannotator.py
> +        return []
If it happens the `on_done` will fail since `on_done` expects `_Clusters`.

2022-05-04 11:52 UTC, PrimozGodec commented on orangecontrib/text/widgets/owannotator.py
> +# from orangecontrib.text.widgets.utils.words import create_words_table - TODO
It can be now uncommented

2022-05-05 07:38 UTC, merged